
= JavaEE - App REST with Jakarta

== Build

Use Maven to build and test:

[source,shell]
----
mvn clean package [optional: verify]
----

Uncomment @RunAsClient and @ExtendWith(ArquillianExtension.class) to run tests without deploying then run test file with Maven, otherwise the Wildfly server must be deployed before starting any API test:

[source,shell]
----
mvn test -Dtest=appAplicationIT
----

Maven will compile the application, provision a WildFly server
The WildFly server is created in `target/server` with the application deployed in it.

== Running the application

To run the application, run the commands:

[source,shell]
----
cd target/server
./bin/standalone.sh
----

To have Wildfly listen to changes in the source files, run the commands:

[source,shell]
----
mvn wildfly:dev
----

The application can be accessed at http://localhost:8080/

== Testing the application

To run integration tests to verify the application, you use Maven:

[source,shell]
----
mvn clean package verify
----

Tests in `src/test` are run against the server in `target/server`.
